name: User Story Validator
description: A user story validation plugin that assesses and vetts user story compliance in codebases
author: https://github.com/james2791
requirements: []
configuration:
  properties:
    propertyone:
      type: string
    propertytwo:
      type: string
    propertthree:
      type: string
  additionalProperties: false

  - label: ":book: User story validation"
    agents:
      queue: outer
    key: us-validation
    plugins:
      - ssh://git@github.com/MotivationalModelling/buildkite-plugin-user-story-validator.git:
        # - ssh://git@github.com:TBPlatform/validator.git#v0.0.1:
          propertyone: $PROPERTY_ONE
          propertytwo: $PROPERTY_TWO
          # propertythree: $PROPERTY_THREE
          
  - label: ":point_up::skin-tone-3: 'Pre-command' to check format"
    command: chmod +x pre-command.sh && ./pre-command.sh

  - label: ":v::skin-tone-3: 'Command' to generate result"
    agents:
       queue: local
    command: chmod +x command.sh && ./command.sh

  - label: "Extra annotation Test"
    command:
      - echo -e "\`\`\`term\nThis is a \033[0;31mtest\033[0m\n\`\`\`" | buildkite-agent annotate