#!/bin/bash

set -euox pipefail
    
    #chmod +x pre-command.sh && ./pre-command.sh
    
    #chmod +x command.sh && ./command.sh

 echo -e "\`\`\`term\nThis is a \033[0;31mtest\033[0m\n\`\`\`" | buildkite-agent annotate